helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-user
    forcestring: true
  - name: image.tag
    value: main@sha256:d16a5c08c5a965537426dcdc59f98fe82436716326f46e1fa16338ad032e0e82
    forcestring: true
