helm:
  parameters:
  - name: image.repository
    value: dungbik/flipnote-user
    forcestring: true
  - name: image.tag
    value: main@sha256:3da05c45f968e38bc92ac48c5d66788f738e0025d6eda2f17414546ead614418
    forcestring: true
