helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-api-gateway
    forcestring: true
  - name: image.tag
    value: main@sha256:7b1d78ab974e1305269aba03ed47accd2dc8075f83eaee42e87f7a8bc16995e1
    forcestring: true
