helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-api-gateway
    forcestring: true
  - name: image.tag
    value: main@sha256:1b5f380e830180c03eface63073981ae7879dac6392741af76e8f3ad5f272314
    forcestring: true
