helm:
  parameters:
  - name: image.repository
    value: dungbik/flipnote-api-gateway
    forcestring: true
  - name: image.tag
    value: main@sha256:b46572626bef4ff3712bcacf771c4e666fc24913e724145b9281fcf36dcc3070
    forcestring: true
