helm:
  parameters:
  - name: image.repository
    value: dungbik/flipnote-api-gateway
    forcestring: true
  - name: image.tag
    value: main@sha256:442e8dd610be1e1d1e967f52b3da56555040a3f16f4f13eb3f4ae7d10f022301
    forcestring: true
