helm:
  parameters:
  - name: image.repository
    value: dungbik/flipnote-image
    forcestring: true
  - name: image.tag
    value: main@sha256:4619ad5214074cf1776e65c02a269c64d11938f11a909894177eb81380784820
    forcestring: true
