apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      {{- if .Values.vault.caBundle }}
      caBundle: {{ .Values.vault.caBundle | quote }}
      {{- end }}
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: {{ .Release.Namespace }}
          key: token
