{{- if .Values.vaultToken }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  token: {{ .Values.vaultToken | quote }}
{{- end }}
